controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_health:
    path: /health/check
    controller: App\Controller\HealthController::check
