controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_health:
    path: /health/check
    controller: App\Controller\HealthController::check

get_rick_and_morty_characters:
    path: /rick-and-morty/characters
    controller: App\Controller\CharactersController::getCharacters
    methods: GET

get_rick_and_morty_characters_count:
    path: /rick-and-morty/characters/count
    controller: App\Controller\CharactersController::getCharactersCount
    methods: GET

get_rick_and_morty_characters_by_ids:
    path: /rick-and-morty/characters/{ids}
    controller: App\Controller\CharactersController::getCharactersByIds
    methods: GET
    requirements:
        ids: \d+(,\d+)*

rick_and_morty_characters_filter:
    path: /rick-and-morty/characters/filter
    controller: App\Controller\CharactersController::getFilteredCharacters
    methods: GET
